// lib/mock-data/departments.ts
import type { Department } from "@/types/department";

export const departments: Department[] = [
    {
        id: "exec",
        name: "Executive Office",
        code: "EXEC",
        parentId: null,
        headId: "u-jane",
        headName: "Jane Doe",
        headInitials: "JD",
        employeeCount: 2,
        location: "Jakarta HQ",
        status: "active",
    },
    {
        id: "eng",
        name: "Engineering",
        code: "ENG",
        parentId: "exec",
        headId: "u-budi",
        headName: "Budi Santoso",
        headInitials: "BS",
        employeeCount: 14,
        location: "Jakarta HQ",
        status: "active",
    },
    {
        id: "eng-qa",
        name: "Quality Assurance",
        code: "ENG-QA",
        parentId: "eng",
        headId: "u-farah",
        headName: "Farah Az-Zahra",
        headInitials: "FA",
        employeeCount: 4,
        location: "Jakarta HQ",
        status: "active",
    },
    {
        id: "design",
        name: "Product Design",
        code: "DSN",
        parentId: "exec",
        headId: "u-citra",
        headName: "Citra Salsabila",
        headInitials: "CS",
        employeeCount: 6,
        location: "Remote",
        status: "active",
    },
    {
        id: "hr",
        name: "Human Resources",
        code: "HR",
        parentId: "exec",
        headId: "u-dimas",
        headName: "Dimas Prakoso",
        headInitials: "DP",
        employeeCount: 3,
        location: "Jakarta HQ",
        status: "active",
    },
    {
        id: "sales",
        name: "Sales",
        code: "SLS",
        parentId: "exec",
        headId: "u-rina",
        headName: "Rina Hartati",
        headInitials: "RH",
        employeeCount: 5,
        location: "Surabaya",
        status: "active",
    },
    {
        id: "finance",
        name: "Finance",
        code: "FIN",
        parentId: "exec",
        headId: null,
        headName: null,
        headInitials: null,
        employeeCount: 4,
        location: "Jakarta HQ",
        status: "inactive",
    },
];

export function getDepartmentById(id: string): Department | undefined {
    return departments.find((d) => d.id === id);
}