import type { Metadata } from "next";
import { Manrope, Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { AuthProvider } from "@/components/auth/AuthProvider";

const manrope = Manrope({
    subsets: ["latin"],
    variable: "--font-manrope",
    weight: ["500", "600", "700"],
});

const inter = Inter({
    subsets: ["latin"],
    variable: "--font-inter",
    weight: ["400", "500", "600"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${manrope.variable} ${inter.variable} h-full antialiased`}
        >
            <body className="font-body bg-primary-tint text-neutral">
                    <AuthProvider>{children}</AuthProvider>
                <Toaster
                    position="top-right"
                    toastOptions={{
                        classNames: {
                            toast: "font-body rounded-lg border border-neutral/15 bg-base-white shadow-sm",
                            title: "text-primary-dark font-medium text-sm",
                            description: "text-neutral text-xs",
                            success: "border-l-4 border-l-success",
                            error: "border-l-4 border-l-danger",
                            warning: "border-l-4 border-l-warning",
                        },
                    }}
                />
            </body>
        </html>
    );
}
